- name: Create user
  hosts: workers
  become: true
  vars:
    user_name: ansible_user
    user_password: "12345678" 

  tasks:
    - name: Create user
      command: useradd -m -s /bin/bash ansible_user
