---
- name: Deploy application with Docker Compose
  hosts: workers
  become: true
  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /opt/docker-compose.yml
    - name: Start Docker Compose
      docker_compose:
        project_src: /opt
        project_name: myapp
        state: present
