- name: Run deploy with k8s
  hosts: workers
  become: true

  tasks:
    - name: Create directory 
      file:
        path: /home/vicheak/deploy
        state: directory
        mode: 0755
    - name: Copy k8s deployment file
      copy:
        src: "./shellscript/wordpress_deploy.sh"
        dest: /home/vicheak/deploy/wordpress_deploy.sh
    - name: Run script to deploy
      command: sh /home/vicheak/deploy/wordpress_deploy.sh