- name: Run deploy with k8s
  hosts: workers
  become: true
  vars:
    registry: "{{ registry }}"
    imageName: "{{ imageName }}"
    tag: "{{ tag }}"
    fullImageName: "{{ registry }}/{{ imageName }}:{{ tag }}"

  tasks:
    - name: Create directory 
      file:
        path: /home/vicheak/deploy
        state: directory
        mode: 0755
    - name: Copy k8s deployment file
      copy:
        src: "./shellscript/spring_deploy.sh"
        dest: /home/vicheak/deploy/spring_deploy.sh
    - name: Run script to deploy
      command: sh /home/vicheak/deploy/spring_deploy.sh "{{ fullImageName }}"